---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-cve-2022-0811
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: localhost:5000/webhook-cve-2022-0811:latest
        name: webhook
        ports:
        - containerPort: 9443
          name: https
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: certs
