---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-cve-2022-0811
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNHRENDQVo2Z0F3SUJBZ0lVSWxRWExpL0tmTm9rR1Fya2huaFQ5UXFJZ2tFd0NnWUlLb1pJemowRUF3SXcKUWpFTE1Ba0dBMVVFQmhNQ1dGZ3hGVEFUQmdOVkJBY01ERVJsWm1GMWJIUWdRMmwwZVRFY01Cb0dBMVVFQ2d3VApSR1ZtWVhWc2RDQkRiMjF3WVc1NUlFeDBaREFnRncweU1qQXpNakV3T1RFeE16RmFHQTh5TURVd01EUXdNekE1Ck1URXpNVm93UWpFTE1Ba0dBMVVFQmhNQ1dGZ3hGVEFUQmdOVkJBY01ERVJsWm1GMWJIUWdRMmwwZVRFY01Cb0cKQTFVRUNnd1RSR1ZtWVhWc2RDQkRiMjF3WVc1NUlFeDBaREIyTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQTJJQQpCRmVla0lNaEduTk5tczBLR1RoNnJTNTN6WnRQUzFOYXBVYnhEZ00yMFQ5cmtHVXFUeUkwR1RrcS9ERGVDeFhLClkyZm9aRFg1THZCYnFsU0JMY1pKL2hyV094RFVVV0lCOXlzR2NuR2lseW05NWZsTVliY2xycG5WdVZXT0Z3TmcKbktOVE1GRXdIUVlEVlIwT0JCWUVGRHZ2emdndTh6TC94d1NNR09JY3JlY2lKQk52TUI4R0ExVWRJd1FZTUJhQQpGRHZ2emdndTh6TC94d1NNR09JY3JlY2lKQk52TUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3Q2dZSUtvWkl6ajBFCkF3SURhQUF3WlFJeEFONTRJdUF0YWV6dkdCQ2tRYmhlUkRBZFBUTU81UlZUcFQ2ajJuWDNEczJyR0Y1UHZ1OXkKZStXRFc3Nmw2amtnZEFJd2ZsdlZvVE9KbEIzT0RZRWVaeStONDU5eFNQSHN0bE5MckFtV2VBeS90YVBHREY5NApybWlBcjl2YitTS3NRKzlJCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook
      namespace: cve-2022-0811
      path: /validate-v1-pod-sysctl
  failurePolicy: Fail
  name: v1.cve-2022-0811.kb.io
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - "kube-system"
        - "cve-2022-0811"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: "Namespaced"
  sideEffects: None
